const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs/promises');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROME_BIN?{executablePath:process.env.CHROME_BIN}:{})});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.goto(process.env.BASE_URL||'http://127.0.0.1:8765/');assert.equal(await page.locator('.claim-card').count(),9);
 await page.locator('#loadExample').click();await page.locator('#newProject').click();await page.locator('[name=title]').fill('团队协作研究');await page.locator('[name=question]').fill('是否采用远程办公？');await page.locator('[name=hypothesis]').fill('远程办公提高团队效率');await page.locator('#editorForm [type=submit]').click();assert.equal(await page.locator('#capex-tab').isVisible(),false);
 await page.locator('[data-view=library]').click();await page.locator('[data-add=sources]').click();await page.locator('[name=title]').fill('团队反馈 <img src=x onerror=alert(1)>');await page.locator('[name=body]').fill('访谈反馈：专注时间增加，但跨团队协作有困难。');await page.locator('[name=url]').fill('https://example.org/report');await page.locator('[name=boundary]').fill('小样本，不证明所有团队适用');await page.locator('#editorForm [type=submit]').click();assert.equal(await page.locator('.library-card img').count(),0);
 await page.locator('[data-view=map]').click();await page.locator('[data-add=claims]').click();await page.locator('[name=title]').fill('专注时间可能增加');await page.locator('[name=text]').fill('基于访谈，目前保留工作假设。');await page.locator('[name=sources]').check();await page.locator('#editorForm [type=submit]').click();assert.equal(await page.locator('#detail .source-button').count(),1);
 await page.locator('[data-view=evidence]').click();await page.locator('[data-add=evidence]').click();await page.locator('[name=title]').fill('跨团队协作成本上升');await page.locator('[name=text]').fill('协调成本可能抵消专注收益');await page.locator('[name=stance]').selectOption('challenge');await page.locator('[name=sources]').check();await page.locator('#editorForm [type=submit]').click();assert.equal(await page.locator('#challenge-list .evidence-card').count(),1);
 await page.locator('[data-view=timeline]').click();await page.locator('[data-add=stages]').click();await page.locator('[name=title]').fill('先做混合办公试点');await page.locator('[name=text]').fill('两类证据需要共同考虑');await page.locator('[name=date]').fill('2026-10-08');await page.locator('[name=change]').fill('从全面采用改为小范围验证');await page.locator('[name=sources]').check();await page.locator('#editorForm [type=submit]').click();
 await page.locator('#conclusionText').fill('先试点，再复核效率与协作指标。');await page.reload();assert.match(await page.locator('#conclusionText').inputValue(),/先试点/);assert.equal(await page.locator('.claim-card').count(),1);
 let download=page.waitForEvent('download');await page.locator('#exportProject').click();const jsonPath=await (await download).path(),project=JSON.parse(await fs.readFile(jsonPath,'utf8'));assert.equal(project.question,'是否采用远程办公？');assert.equal(project.stages.length,1);
 await page.locator('#newProject').click();await page.locator('#cancelEditor').click();await page.locator('#projectFile').setInputFiles(jsonPath);await page.waitForFunction(()=>document.querySelector('#projectQuestion').textContent==='是否采用远程办公？');assert.equal(await page.locator('.claim-card').count(),1);
 download=page.waitForEvent('download');await page.locator('#export').click();const md=await fs.readFile(await (await download).path(),'utf8');assert.match(md,/https:\/\/example.org\/report/);assert.match(md,/先试点/);assert.match(md,/挑战：跨团队/);
 const invalid=structuredClone(project);invalid.sources[0].url='javascript:alert(1)';await page.locator('#projectFile').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(invalid))});await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('导入失败'));assert.equal(await page.locator('#projectQuestion').textContent(),'是否采用远程办公？');
 invalid.sources[0].url='https://example.org';invalid.claims[0].sources=['missing'];await page.locator('#projectFile').setInputFiles({name:'invalid-ref.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(invalid))});await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('找不到'));assert.equal(await page.locator('.claim-card').count(),1);
 await page.locator('[data-view=library]').click();await page.locator('[data-edit=sources]').click();await page.locator('[name=body]').fill('修订后的访谈摘要');await page.locator('#editorForm [type=submit]').click();assert.match(await page.locator('.library-card').textContent(),/修订后/);
 await page.locator('[data-edit=sources]').click();await page.locator('#deleteItem').click();const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('jianwei.workspace.v2')));assert.equal(saved.sources.length,0);for(const kind of ['claims','evidence','stages'])assert.deepEqual(saved[kind][0].sources,[]);
 await page.locator('#loadExample').click();assert.equal(await page.locator('.claim-card').count(),9);for(const width of [1440,1024,800,390]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'overflow '+width);}
 await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:process.env.SCREENSHOT_DIR?process.env.SCREENSHOT_DIR+'/workspace.png':'/tmp/jianwei-workspace.png',fullPage:true});await page.locator('#editProject').click();await page.screenshot({path:process.env.SCREENSHOT_DIR?process.env.SCREENSHOT_DIR+'/editor.png':'/tmp/jianwei-editor.png'});assert.deepEqual(errors,[]);console.log('PASS: editable workspace, linked evidence, persistence, JSON roundtrip, Markdown, invalid imports, safe text, deletion cleanup, responsive layout');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
